<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use DateTime;

class FacilitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
            
             DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '12時間ごとに100円、※ 入場から2時間以内に出場された場合は無料',
            'address' => '熊本県熊本市中央区手取本町1-1',
            'link' => 'https://passurt24.com/bicycle_city_chosha/',
            'phone_number' => '096-354-3611',
            'capacity' => '50台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市庁舎自転車駐車場',
            'latitude' =>32.803565 ,
            'longitude' =>130.708906 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '12時間ごとに100円、※ 入場から2時間以内に出場された場合は無料、',
            'address' => '熊本県熊本市中央区手取本町２−１',
            'link' => 'https://passurt24.com/bicycle_city_choshakita/',
            'phone_number' => '096-354-3611',
            'capacity' => '210台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市庁舎北側自転車駐車場',
            'latitude' =>32.803565 ,
            'longitude' =>130.708906 ,
            ]);
            
            /*DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '自転車　6時間ごとに100円（2時間無料）自動二輪（125㏄以下）　6時間ごとに100円(2時間無料）',
            'address' => '熊本県熊本市中央区下通1-3',
            'link' => 'https://www.jmpsa.or.jp/society/parking/area43/p-14263.html',
            'phone_number' => '096-354-3611',
            'capacity' => '自転車 451台 自動二輪(125㏄以下) 83台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'くまもとまちなか駐輪場下通1丁目',
            'latitude' => 32.802039,
            'longitude' => 130.708902,
            ]);*/
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '自転車 12時間ごとに100円（2時間無料）自動二輪（125㏄） 12時間ごとに100円（2時間無料）',
            'address' => '熊本県熊本市中央区花畑町9-1熊本市役所別館',
            'link' => 'https://passurt24.com/bicycle_siei_city_kumamoto/',
            'phone_number' => '096-354-3611',
            'capacity' => '自転車 340台 自動二輪（125㏄以下）380台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市自転車駐車場',
            'latitude' => 32.802891396393115,
            'longitude' => 130.70723939320783,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '8-21時（20時まで入庫可）',
            'per_hour_fee' => '自転車　当日鶴屋での買い物レシート2160円以上で無料。レシートなしなら1日100円
            　　　　　　　　　　　　　　　　自動二輪　当日鶴屋での買い物レシート2160円以上で無料。レシートなしなら1日200円　　　　　　　　　',
            'address' => '熊本県熊本市中央区手取本町6-1',
            'link' => 'https://www.tsuruya-dept.co.jp/service/parking/index.html',
            'phone_number' => '096-327-3703',
            'capacity' => '自転車 270台 自動二輪（125㏄以下）大型自動二輪車 100台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'鶴屋百貨店駐輪場',
            'latitude' => 32.80236543819347, 
            'longitude' =>130.71099630312833 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '8-21時（20時まで入庫可）',
            'per_hour_fee' => '当日鶴屋での買い物レシート2160円以上で無料。レシートなしなら1日100円',
            'address' => '熊本県熊本市中央区安政町2-5',
            'link' => 'https://www.tsuruya-dept.co.jp/service/parking/index.html',
            'phone_number' => '096-327-3703',
            'capacity' => '90台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'鶴屋安政町駐輪場',
            'latitude' =>32.80170656301667,
            'longitude' => 130.71164226851812,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '12時間ごとに100円（2時間無料）',
            'address' => '熊本県熊本市中央区上通町5-14',
            'link' => 'https://passurt24.com/bicycle_city_kamitori/',
            'phone_number' => '096-354-3611',
            'capacity' => '650台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市上通自転車駐車場',
            'latitude' =>32.80425397546283, 
            'longitude' =>130.7118549220896  ,
            ]);
            
            /*DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '8時間ごとに100円（2時間無料）',
            'address' => '熊本県熊本市中央区中央街6-5',
            'link' => 'https://passurt24.com/bicycle_ginza_place/',
            'phone_number' => '096-354-3611',
            'capacity' => '183台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'くまもとまちなか駐輪場銀座プレス',
            'latitude' => ,
            'longitude' => ,
            ]);*/
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '自転車　8時間ごとに100円（2時間無料）、自動二輪（125㏄以下）4時間ごとに100円（2時間無料）',
            'address' => '熊本県熊本市中央区下通1-12',
            'link' => 'https://www.jmpsa.or.jp/society/parking/area43/p-14265.html',
            'phone_number' => '096-354-3611',
            'capacity' => '自転車 313台 自動二輪（125㏄以下）119台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'くまもとまちなか駐輪場銀座通り',
            'latitude' =>32.79820768163371, 
            'longitude' => 130.70770001622492 ,
            ]);
            
            /*DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '8時間ごとに100円（2時間無料）',
            'address' => '熊本県熊本市中央区城東町5-46',
            'link' => '',
            'phone_number' => '096-354-3611',
            'capacity' => '2832台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'くまもとまちなか駐輪場城東',
            'latitude' => ,
            'longitude' => ,
            ]);*/
            
            /*DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '8時間ごとに100円（2時間無料）',
            'address' => '熊本県熊本市中央区下通2',
            'link' => '',
            'phone_number' => '096-354-3611',
            'capacity' => '360台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'くまもとまちなか駐輪場下通2丁目',
            'latitude' => ,
            'longitude' => ,
            ]);*/
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '8時間ごとに100円（2時間無料）',
            'address' => '熊本県熊本市中央区草葉町1',
            'link' => 'https://passurt24.com/bicycle_kusaba2/',
            'phone_number' => '096-354-3611',
            'capacity' => '184台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'くまもとまちなか駐輪場草場第2',
            'latitude' => 32.80505034367533, 
            'longitude' => 130.7129042337946,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '8時間ごとに100円（2時間無料）',
            'address' => '熊本県熊本市中央区新市街7',
            'link' => '',
            'phone_number' => '096-354-3611',
            'capacity' => '自転車 100台 自動二輪（125㏄）60台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'くまもとまちなか駐輪場新市街第1',
            'latitude' =>32.79882029484949, 
            'longitude' =>130.70523006437205 , 
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '自転車　8時間ごとに100円（2時間無料）、自動二輪（125㏄以下）4時間ごとに100円（2時間無料）',
            'address' => '熊本県熊本市中央区草葉町3',
            'link' => 'https://passurt24.com/bicycle_kusaba1/',
            'phone_number' => '096-354-3611',
            'capacity' => '自転車 159台 自動二輪（125㏄以下）171台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'くまもとまちなか駐輪場草場第1',
            'latitude' =>32.79888342377248, 
            'longitude' =>130.70520860670038  ,
            ]);
        
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '無料',
            'address' => '熊本県熊本市中央区九品寺1-13-21',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車 170台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市銀座橋際自転車駐車場',
            'latitude' =>32.79861256133114, 
            'longitude' =>130.71354422206804  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '6時30分-23時',
            'per_hour_fee' => '自転車　終日100円 自動二輪（125㏄以下）終日150円',
            'address' => '熊本県熊本市中央区坪井2-2-40',
            'link' => 'https://www.kumamotodentetsu.co.jp/ticket/service/bicycleparking.html',
            'phone_number' => '096-343-5035',
            'capacity' => '自転車　200台　自動二輪（125㏄以下）88台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊電藤崎宮駅前駐輪場',
            'latitude' =>32.80913249986846, 
            'longitude' =>130.71334376010552  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県',
            'link' => 'https://www.kumamotodentetsu.co.jp/train/station/07.html',
            'phone_number' => '096-343-5035',
            'capacity' => '台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊電黒髪町駅駐輪場',
            'latitude' => 32.81828641893125, 
            'longitude' => 130.71723352447725,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市中央区国府1-3-1',
            'link' => 'https://www.city.kumamoto.jp/hpkiji/pub/detail.aspx?c_id=5&id=20',
            'phone_number' => '',
            'capacity' => '自転車384台　自動二輪（125㏄以下）3台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市新水前寺駅西高架下自転車駐輪',
            'latitude' => 32.794183203355786, 
            'longitude' => 130.72674311891325,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市中央区水前寺1-380-1',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車　343台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市新水前寺駅東高架下自転車駐輪場',
            'latitude' =>32.794280744730564, 
            'longitude' => 130.72673173340846 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市西区春日3-601',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車　813台　自動二輪（125㏄以下）150台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 3,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市熊本駅南高架下自転車駐輪場',
            'latitude' => 32.789365008957056, 
            'longitude' => 130.68769170646087,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市西区西区春日3-882-12',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車　971台　自動二輪（125㏄以下）126台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 3,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市熊本駅北高架下自転車駐輪場',
            'latitude' => 32.79166479370247, 
            'longitude' =>130.68925644824782 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市西区上熊本3-552',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車　20台　自動二輪（125㏄以下）',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 3,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊電韓々坂駅駐輪場',
            'latitude' =>32.82415290241018, 
            'longitude' => 130.7019045821518 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市西区上熊本3-552',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車300台　自動二輪（125㏄以下）150台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 4,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市健軍変電所前駐輪場',
            'latitude' =>32.78122208406506, 
            'longitude' =>130.76112770672395  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '6時-24時30分',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市東区若葉1-36-6',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車1058台　自動二輪（125㏄以下）144台台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 4,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市健軍自転車駐輪場',
            'latitude' =>32.77723119696149, 
            'longitude' =>130.7616945202181  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市南区富合町志々水151-5',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車163台　自動二輪（125㏄以下）25台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 5,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市富合駅高架下自転車駐車場',
            'latitude' =>32.713994348624915, 
            'longitude' =>130.6734172374088  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市西区春日3丁目601番地8',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車 436台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 3,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市熊本駅中央高架下自転車駐輪場',
            'latitude' => 32.79007037831318, 
            'longitude' =>130.68812881030667, 
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市南区富合町志々水',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車　44台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 5,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市富合駅西口自転車駐車場',
            'latitude' =>32.71393656216555, 
            'longitude' => 130.6733670126021 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市南区島町4-2',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車 350台 自動二輪（125㏄以下）40台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 5,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市西熊本駅自転車駐車場',
            'latitude' =>32.762540354488564, 
            'longitude' =>130.6832734952345  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '5時15分-24時',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市南区島町4-2',
            'link' => 'https://www.musashiduka-bicycle-p.com/',
            'phone_number' => '',
            'capacity' => '自転車 1000台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 2,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市武蔵塚駅前自転車駐車場',
            'latitude' =>32.85114237551196, 
            'longitude' => 130.77126945089282 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市北区武蔵ケ丘（武蔵塚駅前）',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自動二輪（125㏄以下）40台 大型自動二輪 40台',
            'bicycle' => '不可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '可',
            'receipt' => '不可',
            'region_id' => 2,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'武蔵塚駅前バイク置き場',
            'latitude' => 32.84924774641717, 
            'longitude' => 130.7691338117335,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '自転車 8時間ごとに100円　自動二輪（125㏄以下）4時間ごとに100円',
            'address' => '熊本県熊本市中央区下通２丁目５−４',
            'link' => 'https://passurt24.com/bicycle_showerdori/',
            'phone_number' => '096-354-3611',
            'capacity' => '自転車 200台 自動二輪（125㏄以下）128台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'くまもとまちなか駐輪場シャワー通り',
            'latitude' =>32.798430780279574, 
            'longitude' =>130.70773135090184  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '自転車 12時間ごとに100円　自動二輪（125㏄以下）6時間ごとに100円',
            'address' => '熊本県熊本市中央区下通１丁目２−４',
            'link' => '',
            'phone_number' => '096-354-3611',
            'capacity' => '自転車 451台 自動二輪（125㏄以下）83台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'パスート24サイクルパーク下通1丁目',
            'latitude' => 32.802681241283025, 
            'longitude' => 130.70832703554805,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '自転車 12時間ごとに100円',
            'address' => '熊本県熊本市中央区花畑町１１−１３',
            'link' => 'https://passurt24.com/bicycle_sakaedori/',
            'phone_number' => '096-354-3611',
            'capacity' => '自転車 84台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'サイクルパーク栄通り',
            'latitude' =>32.80151180765941, 
            'longitude' =>130.70722961590883  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '大型自動二輪 1時間ごとに100円　最大料金500円（12時間ごとに最大料金が加算）',
            'address' => '熊本県熊本市中央区花畑町２−２',
            'link' => 'https://passurt24.com/car_hanabata_coin/',
            'phone_number' => '096-325-6680',
            'capacity' => '大型自動二輪 20台',
            'bicycle' => '不可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'パスート24花畑コイン',
            'latitude' =>32.80270284424475, 
            'longitude' => 130.70581146441793 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '大型自動二輪 1時間ごとに100円　最大料金500円（12時間ごとに最大料金が加算）',
            'address' => '熊本県熊本市中央区下通1-10',
            'link' => '',
            'phone_number' => '092-271-6400',
            'capacity' => '大型自動二輪 10台',
            'bicycle' => '不可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'下通1丁目駐車場（バイクパーキング）',
            'latitude' =>32.80008994523158, 
            'longitude' => 130.7093743836862 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '大型自動二輪　1時間100円、12時間ごとに300円、24時間まで500円',
            'address' => '熊本県熊本市西区春日３丁目１５−１',
            'link' => '',
            'phone_number' => '',
            'capacity' => '大型自動二輪 20台',
            'bicycle' => '不可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '可',
            'receipt' => '可',
            'region_id' => 3,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本駅バイク駐車場',
            'latitude' => 32.79153845193974, 
            'longitude' =>130.68995837788242 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '自転車 8時間ごとに100円 自動二輪（125㏄以下）6時間ごとに100円',
            'address' => '熊本県熊本市中央区桜町3番10号',
            'link' => 'https://sakuramachi-kumamoto.jp/access#bike',
            'phone_number' => '096-354-1111',
            'capacity' => '自転車 402台 自動二輪（125㏄以下）98台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'SAKURA　MACHI　Kumamoto駐輪場',
            'latitude' =>32.80123504171389, 
            'longitude' =>130.70251088504548  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '自動二輪（125㏄以下）60分ごとに100円 24時間最大600円 大型自動二輪 ）60分ごとに100円 24時間最大600円',
            'address' => '熊本県熊本市中央区水道町12-1',
            'link' => 'https://parkcity24.jp/park-shirakawa.html',
            'phone_number' => '096-355-9922',
            'capacity' => '15台',
            'bicycle' => '不可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'パークシティ24h白川公園',
            'latitude' =>32.80406621168036, 
            'longitude' => 130.71397150489543 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '自転車 8時間ごとに100円（2時間無料） 自動二輪（125㏄以下）・大型自動二輪 60分ごとに100円 24時間最大600円',
            'address' => '熊本県熊本市中央区水道町10-11',
            'link' => 'https://parkcity24.jp/park-suidocho.html',
            'phone_number' => '096-355-9911',
            'capacity' => '自転車 110台 自動二輪（125㏄以下）・大型自動二輪 23台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'パークシティ24h　水道町',
            'latitude' =>32.80352352836049, 
            'longitude' => 130.7139674573693 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市中央区水道町10-11',
            'link' => 'https://www.city.kumamoto.jp/hpkiji/pub/detail.aspx?c_id=5&id=20',
            'phone_number' => '',
            'capacity' => '自転車 50台 自動二輪（125㏄以下）・大型自動二輪 12台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '可',
            'receipt' => '不可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'本庄駐輪場（地域医療絵センター南側）',
            'latitude' => 32.79332195772941, 
            'longitude' => 130.70742085570356,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市中央区南熊本3丁目14',
            'link' => 'https://www.city.kumamoto.jp/hpkiji/pub/detail.aspx?c_id=5&id=20',
            'phone_number' => '',
            'capacity' => '自転車250台 自動二輪（125㏄以下）・大型自動二輪 50台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '可',
            'receipt' => '不可',
            'region_id' => 5,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'南熊本駅前自転車駐輪場',
            'latitude' =>32.78595664066438, 
            'longitude' =>130.71197641517983  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市中央区平成１',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車 900台 自動二輪（125㏄以下）・大型自動二輪 100台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '可',
            'receipt' => '不可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市平成駅自転車駐輪場',
            'latitude' =>32.781462243211394, 
            'longitude' =>130.7035442104174  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市中央区出水1-8-2',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車 80台 自動二輪（125㏄以下）20台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'水前寺児童公園前駐輪場',
            'latitude' =>32.788364509305644, 
            'longitude' =>130.73466080858194  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市中央区水前寺6-6-2',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車 900台 自動二輪（125㏄以下）100台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本県庁駐輪場',
            'latitude' =>32.78915184646809, 
            'longitude' =>130.74072910672186  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市東区新生1-1',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車 54台',
            'bicycle' => '可',
            'bike_under_125cc' => '不可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 4,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'庄口公園前駐輪場',
            'latitude' =>32.78037732515356, 
            'longitude' => 130.75484529991246 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市北区下硯川町1806-1西里駅',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自 転車37台 自動二輪（125㏄以下）5台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 2,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'西里駅前駐輪場',
            'latitude' =>32.85484810585525, 
            'longitude' =>130.69997605089688  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市北区弓削18',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車 155台 自動二輪（125㏄以下）15台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 2,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'光の森駅自転車駐輪場',
            'latitude' =>32.85769496152904, 
            'longitude' => 130.78694567976123 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市西区田崎本町１－１７',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車 40台 自動二輪（125㏄以下）10台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '不可',
            'region_id' => 3,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'田崎橋自転車駐輪場',
            'latitude' =>32.78541197599243, 
            'longitude' => 130.68762343556318 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '終日無料',
            'address' => '熊本県熊本市北区植木町荻迫62-8',
            'link' => '',
            'phone_number' => '',
            'capacity' => '自転車 175台 自動二輪（125㏄以下）・大型自動二輪 51台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '可',
            'receipt' => '不可',
            'region_id' => 2,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市植木駅自転車駐車場',
            'latitude' => 32.88040892169536, 
            'longitude' =>130.68132128712 ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '8時から22時30分（最終入庫21時30分）',
            'per_hour_fee' => '2時間まで100円（それ以降1時間ごとに50円加算）',
            'address' => '熊本県熊本市中央区二の丸1-14',
            'link' => 'http://www.sakuranobaba-johsaien.jp/access/',
            'phone_number' => '096-322-5060（9:00~17:30）',
            'capacity' => '自動二輪（125㏄以下）30台 大型自動二輪 24台',
            'bicycle' => '不可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'桜の馬場駐車場',
            'latitude' =>32.80559995910776, 
            'longitude' =>130.7079611455867  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '自転車 12時間ごとに100円 自動二輪（125㏄以下）8時間ごとに100円',
            'address' => '熊本県熊本市中央区花畑町１１－２',
            'link' => 'https://passurt24.com/bicycle_shiromichodori/',
            'phone_number' => '096-354-3611',
            'capacity' => '自転車 65台 自動二輪（125㏄以下）70台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '不可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'サイクルパーク城見町通り',
            'latitude' =>32.80238784895843, 
            'longitude' =>130.70738966622332  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '24時間',
            'per_hour_fee' => '300円（前払い制）',
            'address' => '熊本県熊本市中央区中央外6-9',
            'link' => '',
            'phone_number' => '080-3908-9578',
            'capacity' => '自動二輪（125㏄以下）・大型自動二輪 10台',
            'bicycle' => '不可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'ODA　MOTORCYICLE　PARKING',
            'latitude' =>32.79994919348787, 
            'longitude' =>130.71040527262736  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '7時-23時（金・土曜日と祭日の前日は午前0時まで営業）',
            'per_hour_fee' => '3時間まで200円、それ以降1時間ごとに100円',
            'address' => '熊本県熊本市中央区南坪井町8-21',
            'link' => '',
            'phone_number' => '096-359-0002',
            'capacity' => '5台',
            'bicycle' => '不可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'香川駐車場',
            'latitude' =>32.80825449457639, 
            'longitude' =>130.71364895882402  ,
            ]);
            
            DB::table('facilities')->insert([
            'opening_time' => '7時-25時',
            'per_hour_fee' => '12時間ごとに100円（2時間無料）定期利用 一般2000円1か月、5700円3か月　学生1000円1か月、2850円3か月　障碍者1000円1か月、2850円3か月 自動二輪（125㏄以下）6時間ごとに100円（2時間無料） 定期利用　一般4000円1か月、11400円3か月　障がい者2000円1か月　5700円3か月　大型自動二輪　2時間ごとに100円',
            'address' => '熊本県熊本市中央区辛島町1',
            'link' => 'https://k-c.passurt.com/bicycle',
            'phone_number' => '096-328-2923',
            'capacity' => '自転車 314台 自動二輪（125㏄以下）160台 大型自動二輪 30台',
            'bicycle' => '可',
            'bike_under_125cc' => '可',
            'bike_more_125cc' => '可',
            'receipt' => '可',
            'region_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
            'name' =>'熊本市辛島公園地下自転車駐車場',
            'latitude' =>32.79888384220735, 
            'longitude' => 130.7049659540905 ,
            ]);
            
    }
}